apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dallinw-com
  namespace: ambassador
spec:
  secretName: ambassador-certs
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: dallinw.com
  dnsNames:
    - dallinw.com