apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: dallinw-com
  namespace: ambassador
spec:
  acmeProvider:
    authority: 'https://acme-v02.api.letsencrypt.org/directory'
    email: dallin@dallinw.com
  hostname: dallinw.com
  tlsSecret:
    name: ambassador-certs